name: 构建和发布内核

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    name: 构建和发布内核
    runs-on: ubuntu-22.04  # 指定使用 Ubuntu 22.04 系统

    steps:
    - name: 检出仓库
      uses: actions/checkout@v3

    - name: 设置 Git
      run: |
        git config --global user.name "liqideqq"
        git config --global user.email "atimor@126.com"

    - name: 设置构建环境
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential ccache curl flex git gnupg gperf imagemagick \
          lib32ncurses5-dev lib32readline-dev liblz4-tool libncurses5 libncurses5-dev \
          libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool \
          squashfs-tools xsltproc zip zlib1g-dev g++-multilib gcc-multilib lib32z1-dev

    - name: 安装 repo 工具
      run: |
        mkdir -p ~/.bin
        curl -o ~/.bin/repo https://mirrors.tuna.tsinghua.edu.cn/git/git-repo
        chmod a+rx ~/.bin/repo
        echo 'export PATH=$PATH:~/.bin' >> $GITHUB_ENV

    - name: 克隆内核仓库并运行构建脚本
      run: |
        # 确保脚本具有执行权限
        chmod +x ./AIO_GKI_build_kernel_release.sh

        # 执行构建脚本
        ./AIO_GKI_build_kernel_release.sh

    - name: 创建发布版本
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}"
        release_name: "GKI 内核与 KernelSU & SUSFS"
        body: |
          由 GitHub Actions 自动发布。
          包含以下构建：
          $(find ./builds -type f -name "*.zip" -exec basename {} \;)
        draft: false
        prerelease: false

    - name: 上传发布资产
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./builds
        asset_name: build-artifacts.zip
        asset_content_type: application/zip

    - name: 压缩构建产物
      run: |
        cd builds
        zip -r ../build-artifacts.zip ./*
